### ISSUE TITLE
Xcode Compiled Version crashing when opening iNDS settings

### ISSUE THREAD

**Issue by OkazakiTheOtaku** [WilliamLCobb/iNDS#1]
**iPhone 5s, iOS 9.1, Non-Jailbroken**

I self-signed a version of iNDS with Xcode, and attempting to open the settings pane crashes the app. Everything else works perfectly, however.

**Not sure if this helps, but in Xcode the debug session reports this:**

*2015-11-27 23:35:10.008 iNDS[649:166849] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: '-[UITableViewController loadView] loaded the "c3c-6p-wCh-view-5Dk-6y-Z7d" nib but didn't get a UITableView.'
*** First throw call stack:
(0x184d78f48 0x19983bf80 0x184d78e90 0x18a417ac8 0x18a30bd44 0x18a30bc9c 0x18a6a9108 0x18a666844 0x18a663254 0x18a5bc56c 0x18a5c94bc 0x18a2fd984 0x184d2fbd0 0x184d2d974 0x184d2dda4 0x184c5cca0 0x18fe98088 0x18a374ffc 0x100177a5c 0x19a08a8b8)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)*

**Comment by WilliamLCobb** [comment]
I accidentally linked the settings tableview to a table cell. Should be fixed now
