### ISSUE TITLE
INDS 1.1.2 not recognize any rom extension now.

### ISSUE THREAD

**Issue by brujo5** [WilliamLCobb/iNDS#10]
INDS 1.1.2 not recognize any rom extension (rar/nds) unplayable.
Thanks

**Comment by WilliamLCobb** [comment]
The app was supposed to move all .nds and save files to a new iNDS folder inside of documents. It seems like it didn't move it on a few peoples devices though, I'm not sure why.

When you say it doesn't recognize extensions, can you not open games in the app or can you just not see them in your roms list?

**Comment by brujo5** [comment]
just not see them in roms list. Roms are placed in var/mobile/documents/
tried .nds,7z,rar,zip still romlist appear empty.

**Comment by WilliamLCobb** [comment]
There should be and iNDS folder in there where you can place .nds files. You have to use open in for rar, zip, and 7z

Sent from Outlook




On Sun, Dec 6, 2015 at 5:12 PM -0800, "brujo5" <notifications@github.com> wrote:












just not see them in roms list. Roms are placed in var/mobile/documents/

tried .nds,7z,rar,zip still romlist appear empty.

**Comment by brujo5** [comment]
yeah tried to placed rom in var/mobile/documents/inds/ 

placed .nds files in there. open inds app and still apear empty.

**Comment by brujo5** [comment]
not sure why but is fixed after deleting the preferense plist via icleaner. then respring. 
the cheat engine and custom layout is still in progress? thanks
