### ISSUE TITLE
ROMs Slow Down

### ISSUE THREAD

**Issue by Vonderhaarr** [WilliamLCobb/iNDS#100]
All of the ROMs I own keep slowing down after loading and running normally for the first 30 seconds. I am not experiencing this with the emulator my pc and I was wondering if there is a fix for this.

**Comment by essiw** [comment]
Try waiting when opening the app until it states "synching complete". Does that work?

**Comment by DarknesGaming** [comment]
That seems like a huge problem. Maybe @WilliamLCobb will get to that, because I also experienced the same thing.

**Comment by WilliamLCobb** [comment]
I think this has to do with the processor heating up. I'm not 100% sure but when iOS detects an application is using a ton of power (which iNDS does) or the processor starts rising in temperature, it will automatically throttle the CPU. There's really not much I can do to fix this if I'm right but I'll make sure to check it out. 

Does changing games when it starts slowing down fix anything?

**Comment by DarknesGaming** [comment]
I'm going to assume @Vonderhaarr will say yes to that, because doing that fixed my problem.

**Comment by Vonderhaarr** [comment]
This hasn't fixed my problem. Maybe my 5C isn't powerful enough to run this yet. I'll keep trying different things to fix this though.

**Comment by DarknesGaming** [comment]
The iPhone 5C is just as powerful as the iPhone 5. The NORMAL iPhone 5. The only thing that's different is the fact that it's incredibly colorful.
The iPhone 5C is powerful enough, but the ROMs slowing down hard is not something that nds4ios did. It is so weird.

**Comment by DarknesGaming** [comment]
@WilliamLCobb what do you think?

**Comment by DarknesGaming** [comment]
@Vonderharr this issue should be fixed now. The slow down problem in 1.5.1 is also fixed, resulting in 1.5.1 build 2

**Comment by Vonderhaarr** [comment]
@DarknesGaming I'll quickly check if it's working and I'll close the issue if it does. Thanks for the notice!

**Comment by Vonderhaarr** [comment]
@DarknesGaming I have updated my application and this has made the lag/slowing down of the ROM's much worse. Right upon loading up any ROM I am greeted with laggy music and a flashy screen. Not sure if I installed it wrong or if it's the actual program. I installed it normally by opening the Xcode workspace file and signing with my apple ID and running on my phone. Is there any additional steps to this that I have to complete for it to be working fine?

**Comment by WilliamLCobb** [comment]
You're probably on the debug build configuration, try changing the scheme to iNDS release or just redownload the source. I changed it to default to release

**Comment by DarknesGaming** [comment]
Good to know you changed it. Except when I compiled the source, I got debug mode instead. I changed the AppIcon to the normal one, and there was no .debug suffix in the Bundle ID. I did not add the suffix, so why did I get Debug mode?

**Comment by Vonderhaarr** [comment]
@WilliamLCobb I am also getting the Debug Mode pop-up when I install the app. Can you please specify how to change the scheme to the default one because I re-downloaded the source and still got debug mode even though I changed something in the project to "Release" instead of "Debug".

**Comment by Vonderhaarr** [comment]
@WilliamLCobb I have fixed the "Debug" mode thing but now I am getting some graphical and audio lag at parts if games where the graphics are a little bit fancy (including intros). On games like pokemon, all I ever get is the constant flashing of a white screen. Changing the filter did not fix my white screen errors but I do not get them on other games like Hot Wheels: Beat That. I'm still stuck at my original problem here and have no idea what's happening. Is this also still happening to you @WilliamLCobb or am I just unlucky?

**Comment by Vonderhaarr** [comment]
Some quick screenshots of the FPS ![](http://i.imgur.com/6sPN6FY.jpg)![](http://i.imgur.com/MdOXvzC.jpg)![](http://i.imgur.com/pmWfcrk.jpg)

**Comment by DarknesGaming** [comment]
I can most definitely help fix this. I just edited the scheme so when you press "Run" or the play button on Xcode, iNDS will be compiled and installed to your device on release configuration instead of debug. This will be added to the wiki for future builders.

**Comment by Vonderhaarr** [comment]
@Darknessgaming don't know if you were talking to me here but that's what I did and I saw no difference

**Comment by DarknesGaming** [comment]
That's because I did not have time to upload that new Xcode thing. And edit the wiki.

**Comment by Vonderhaarr** [comment]
I guess I'll try and fix this on my own the best I can if nothing is being done right now.

**Comment by WilliamLCobb** [comment]
Different parts of applications run at different speeds. Menus will run much faster than actual gameplay. Similar to the menu in a real game vs when you start playing. If you stay on the menu the fps shouldn't drop

**Comment by Vonderhaarr** [comment]
So if I stay on the menu long enough then play the game it shouldn't drop? I'll try it

**Comment by WilliamLCobb** [comment]
No I mean it's not a big it just how it works. The only fix is to make the emulator run faster
