### ISSUE TITLE
Dropbox refuses to sync

### ISSUE THREAD

**Issue by FrostyFoxie** [WilliamLCobb/iNDS#103]
It says "too many attempts, try again later". It is like an endless loop! How do I fix this? Im running dropbox and inds on the lastest versions now.

**Comment by DarknesGaming** [comment]
@FrostyFoxie I think this is because @WilliamLCobb changed the dropbox code again. Give him time to work on it.

**Comment by WilliamLCobb** [comment]
The dropbox requests have gone from ~20,000 a day to around 300,000 so I'm assuming dropbox is just limiting the number of requests per app. Reopen this issue if it doesn't correct itself in a few
