### ISSUE TITLE
iNDS cheats crashing 

### ISSUE THREAD

**Issue by DarkSpeedySonic** [WilliamLCobb/iNDS#104]
Now to specify, this might be an error with 1 or 2 of 3 things.
1. Device
2. The emulator 
3. The source of which you got the emulator 
There may be a few more origins to the bug but that's all i can think of for now.
Anyways, what seems to happen is; if I put on more than I'd say three cheats (default or added in, iNDS crashes and is not openable until reinstalled or deleted. Currently this has been happening on Pokémon Platinum and mostly Pokémon HeartGold. HeartGold had its own set of rom issues which has a whole entire other poll. The version of iNDS I am currently running is unknown to me but I got it from iEmulators. I'm running the app on an iPhone 5s, iOS 9.3.1 (I believe). I'm also non jail broken hence the iEmulators website. If someone could look into this for me, that would be appreciated. Thank you

**Comment by DarknesGaming** [comment]
The device does not seem to be the problem. If you got iNDS from iEmulators, you got Version 1.4.0. @WilliamLCobb probably patched this already in 1.5.0, but if not that means more bugs for him to fix.

**Comment by DarkSpeedySonic** [comment]
Alright thanks

**Comment by DarknesGaming** [comment]
To get iNDS 1.5.2 (the latest), you have to compile the source code with Xcode. There are instructions on how to do that. If you don't have a Mac, use VMware and a Virtual Disk Image from xBytez.

**Comment by DarkSpeedySonic** [comment]
Unfortunately I don't own a computer. I'll just wait for iEmulators to put it out, although it may take a while.

**Comment by DarkSpeedySonic** [comment]
Hey Darknesgaming can you confirm the multiple cheats crash on your device for me because it might be the update which you stated.

**Comment by DarknesGaming** [comment]
Not crashing at all. I have 6 cheats on.

**Comment by DarkSpeedySonic** [comment]
Thanks :D I'm glad. Hopefully iEmulators puts the update out soon. So I'm a little new to github, should I close the issue?

**Comment by WilliamLCobb** [comment]
The crashing is probably due to a certain cheats or a bad combination. And like @DarknesGaming the infinite crash loop is fixed in 1.5.0
