### ISSUE TITLE
A handy but complicated addition? *Not an issue*

### ISSUE THREAD

**Issue by DarkSpeedySonic** [WilliamLCobb/iNDS#107]
So I've been complaining about cheats and things with iNDS version 1.4.0. But I think a neat addition to the settings of the emulator itself would be an update button, I decided to ask because GBA4iOS had something similar to that. Basically it updates the application to its latest version without having to delete games, saves, cheats, or the application itself and then redownloading it, etc... It just updates it to the latest version. I think it's possible. Also we wouldn't have to worry about these things. Just a convenience thing nothing more.

**Comment by essiw** [comment]
You do not have to delete the game to install an update. Just install it when the game is not deleted and it will overwrite the game, but not the data/games that you have.

**Comment by DarkSpeedySonic** [comment]
Oh, hmmm, never thought about that. Alright. Is there an estimated time on how long iEmulators takes to update there stuff because I'm just a little annoyed. Wanna play platinum and catch Arceus without issue ;-;

**Comment by WilliamLCobb** [comment]
Usually it's about a month. If you or someone you know has a Mac though you can update at any time for free

**Comment by DarkSpeedySonic** [comment]
When did the newest update come out?

**Comment by DarkSpeedySonic** [comment]
Or a better question is, will that be anytime soon. XD

**Comment by essiw** [comment]
I don't think @WilliamLCobb has any influences on the release schedule of iEmulators.

**Comment by DarkSpeedySonic** [comment]
True, the people running the website probably have better things to do, I'll wait but this app is amazing, I don't want this app to be ruined by dumb bugs, keep doing what your doing @WilliamLCobb

**Comment by DarknesGaming** [comment]
@essiw is right about @WilliamLCobb not having any influence on the iEmulators thing. Mostly.
Plus, it would be useful for those without a Mac, or a computer that supports Virtualization software.

**Comment by WilliamLCobb** [comment]
They have to buy enterprise certificates from a black market and that is apparently pretty hard. Sometimes it takes a few days and sometimes It takes a few weeks. I messaged the owner and told him a new version is up so hopefully he'll update it soon
