### ISSUE TITLE
What Happened to the .rar support?

### ISSUE THREAD

**Issue by syn717** [WilliamLCobb/iNDS#108]
Ever since I updated iNDS to 1.5.0-2, I am unable to open .rar files.

I am currently using a jailbroken device
And my iOS version is 9.1

**Comment by syn717** [comment]
I am also using the iPhone 6s too

**Comment by DarknesGaming** [comment]
That's odd. Normally, iNDS supports those files.
You are on the latest version right? Check Cydia to make sure.

**Comment by WilliamLCobb** [comment]
Because the Unrarkit library must be embedded, it cannot be used with services that sign their own apps (such as the build store). I accidentally uploaded the source with it disabled. Try redownloading and installing
