### ISSUE TITLE
Save/Load state doesn't work properly

### ISSUE THREAD

**Issue by inpuu** [WilliamLCobb/iNDS#113]
I had built the latest 1.5.1 version from xcode today.
But save/load state does't work properly.
If I load state which state was saved in the latest version, I can see two results. The first, just white screens appear and I can't keep playing anymore. The second, it loaded properly and I can play the game but there is no sound. I think the process of save state has a problem. Can you check it please?

**Comment by DarkSpeedySonic** [comment]
This has been an issue since 1.4.0. I'm currently on that version and I'm not sure why it's happening. We'll just have to wait and see what @WilliamLCobb has to say.

**Comment by alexElamine** [comment]
The same thing is happening to me. When I try to even launch the game normally it won't work. It's just a white screen. Actually, only the pause state and at times the auto save work.

**Comment by WilliamLCobb** [comment]
Was due to the GPU changes when I added filters. It's fixed in 1.5.1.1 which I'll release soon
