### ISSUE TITLE
close lid

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#114]
It would be cool if the close lid option got activated when turning the device over or when locking the device, it would be cool to hear mario say bye bye when doing this.

**Comment by WilliamLCobb** [comment]
Thats a good idea and would be much nicer than the current lid close

**Comment by WilliamLCobb** [comment]
I changed it to this, It will be in the next version

**Comment by pmp174** [comment]
Wow you're great!!

**Comment by benihana7** [comment]
So what's the method? Is it turn phone over or lock the device? Neither seem to work. I'm running 1.5.4 non-jailbroken on iPhone 6 running iOS 9.3.3

**Comment by Voussoiir** [comment]
I have 1.5.3.2 iNDS Version and closing lid function is not working when locking the device or rotating the device. Can you please tell me how to do it?

**Comment by artfulltruth** [comment]
Hey. Any updates? I dont see any option to close the lid and the above suggestions did not work. Also using 1.5.3.2  Please help
