### ISSUE TITLE
iPhone 5 inds

### ISSUE THREAD

**Issue by shiun1234** [WilliamLCobb/iNDS#116]
iPhone 5 can run inds on full speed?

**Comment by essiw** [comment]
Why ask? Just try it out :)

**Comment by shiun1234** [comment]
I'm just try but my speed just on 40-45 onli

**Comment by DarknesGaming** [comment]
It runs at nearly full speed.

**Comment by shiun1234** [comment]
It still slow...hope inds still can improve the speed

**Comment by shiun1234** [comment]
My inds isn't has any filter setting or mic lo..wat ur inds version

**Comment by DarknesGaming** [comment]
What iNDS are you on?

**Comment by shiun1234** [comment]
Version 1.4.0

**Comment by DarknesGaming** [comment]
The latest version of iNDS (1.5.1.1) is faster but you have to turn off the filter to gain that boost in speed. You can either wait for iEmulators, or compile the source code right now with Xcode.

**Comment by WilliamLCobb** [comment]
iPhone 5 is not powerful enough to run at full fps. Only iPhone 6 and up
