### ISSUE TITLE
Freeze and Permanent Crash

### ISSUE THREAD

**Issue by Scorch666** [WilliamLCobb/iNDS#123]
I'm playing a ROM hack of HGSS and aside from the texture glitch I've also been running into random freezing that forces me to redownload everything entirley to fix that whole "open app quits instantly" thing. I've got it all backed up to Dropbox, so I keep my progress, but having to redownload everything (including getting my ROM in through iTunes) is a huge pain. I've poked around on Github a bit and it seems to be a revoked certificate problem. If I buy a Buildstore account, will it fix these random freezes?

**Comment by DarknesGaming** [comment]
That won't always work, and would you actually buy a BuildStore account just to download one app that might be outdated?
You can also try using a Mac (or VMware and a Mac OS X Virtual Disk) to compile this source code with Xcode. I recommend looking at our wiki to learn how to do that. The instructions were recently edited by me so nobody asks questions when they get to the confusing steps.

**Comment by Scorch666** [comment]
Can I get that link?

**Comment by Scorch666** [comment]
Also, what would Buildstore do for me in regards to these crashes?

**Comment by WilliamLCobb** [comment]
It's bug with crash reporting in the version iEmulators has. The buildstore has an updated version that fixes the problem but it costs $10 a year
