### ISSUE TITLE
Silent button ignored

### ISSUE THREAD

**Issue by fullsaildan** [WilliamLCobb/iNDS#124]
Compiled 1.5.1.2 for 9.3 and Iphone 6. Music continues to play when the phone is on silent. Can turn the ringer volume down to mute and that does work.

**Comment by DarknesGaming** [comment]
Yeah. That's kind of a problem. Unless you're at a press conference, which makes it a big problem.
I'm analyzing iNDS right now. I have the same phone as you, and so far, energy impact is very high.

**Comment by WilliamLCobb** [comment]
So on iOS you can't just say "I want to ignore or follow the mute button" or "I want to use both the microphone and speaker but mute the speaker if there is already sound playing." Apple instead decided forcing apps to use 1 of a few preset configurations was a good idea. So when I added microphone support I had to follow a different configuration which gives me no indication of whether the mute button is on or off. The only way to tell is by using hacky workarounds. 

I've been caught a few times though with the volume up in class and it sucks so I'm going to take another look and see if there's something I can change to respect the mute button.

**Comment by DarknesGaming** [comment]
I hope so, because I don't want my phone to play any audio when it's on silent (which is enabled 24/7). Seriously, I want to protect the fresh speakers on my phone.

**Comment by DarknesGaming** [comment]
I think it's fixed. Also, that means downloading the entire source code again.
