### ISSUE TITLE
Random mini freezes

### ISSUE THREAD

**Issue by peter961785** [WilliamLCobb/iNDS#125]
I've notice that when playing a roms it would sometimes randomly freeze for a brief second and fixes itself after. When this happens it doesn't show any drop in frame rate as well normally 55-60.
iOS 9.3.1 buildstore version:1.5.1.2 (no rar) iPhone 6

**Comment by WilliamLCobb** [comment]
This is the game autosaving. Unfortunately it has to pause in order to save the game. This can be fixed by turning off auto save in the settings
