### ISSUE TITLE
Fps problems

### ISSUE THREAD

**Issue by billyheart** [WilliamLCobb/iNDS#127]
I am not able to get full 60 fps as I play my games as I play the average fps I get is about 15 to 32 fps any help to get my game running normally ??

**Comment by billyheart** [comment]
I need you to solve this plz

**Comment by IcYGodZ** [comment]
Are you jailbroken?

**Comment by WilliamLCobb** [comment]
If you're not on an iphone 6 or above (or the equivalent ipad/ipod) the emulator won't run full speed. Turning on frame skipping may help but you probably still won't be at 60 fps.

**Comment by DarknesGaming** [comment]
The iPhone 5s can run iNDS at full speed, and the iPad mini 2 is the equivalent of that. Some ROMs require more reaources than others.
