### ISSUE TITLE
Repeatedly crashing

### ISSUE THREAD

**Issue by seanbalcarres** [WilliamLCobb/iNDS#128]
Downloaded inds from iemulators and the day after I have downloaded it I go to open it and I get the infinite crash loop.. Anyone know of any fixes?

**Comment by WilliamLCobb** [comment]
The only fix is to install the app from somewhere besides iEmulators or wait until they update it.

You can use XCode if you have a mac or buildstore if you want to pay $10. I'm working on an alternative right now though that's free

**Comment by seanbalcarres** [comment]
Thanks man I'll start roaming the Internet for another download link. Yeah a free alternative is always a popular choice

**Comment by IcYGodZ** [comment]
I wish people tried to sneak in emulators in the app store xD it would be great 😭

**Comment by DarknesGaming** [comment]
Someone did. There was an app called Floppy Cloud. There was an emulator hidden in the app. Apple found out about it fairly quickly.

**Comment by IcYGodZ** [comment]
Yeah but the funny part is: If you downloaded the app before apple takes it out the app store, you keep it forever. It won't crash lol

**Comment by DarknesGaming** [comment]
I missed out on that. It's too bad. For me.
And now, back to Lightning GIT because I'm bored. Why would @WilliamLCobb need i386 code in iNDS anyway? The earliest iPhone, iPad and iPod touch that can support iOS 8.1 runs on the ARM architecture, so i386 would be a bit of a stretch in maintaining compatibility.

**Comment by WilliamLCobb** [comment]
Please keep discussions relevant to the issue. This doesn't belong here. i386 was for the simulator
