### ISSUE TITLE
Close Lid function is missing

### ISSUE THREAD

**Issue by inpuu** [WilliamLCobb/iNDS#133]
I'm playing Hotel Dusk Room 215 now, and I have to use 'close lid' function for a puzzle. I think I saw it before(maybe 1.5.0?), but can't find it now.

**Comment by DarknesGaming** [comment]
That function is gone? That's not good.
Did you go into the settings while you were playing the ROM? That might be why you can't find it.

**Comment by essiw** [comment]
It should be still there, try rotating your device or locking your device, this should work.

see this issue:
https://github.com/WilliamLCobb/iNDS/issues/114

**Comment by inpuu** [comment]
@essiw Thank you!
