### ISSUE TITLE
Rar support

### ISSUE THREAD

**Issue by mcat115** [WilliamLCobb/iNDS#135]
When will support for rar files return to iNDS?

**Comment by mcat115** [comment]
If you want to play a game that is a rar file you can convert to be usable by converting it using file hub

**Comment by DarknesGaming** [comment]
ROMs aren't normally in RAR format. Why would we need RAR support?

**Comment by essiw** [comment]
^because rar is an often used compression standard, files on the internet are often compressed.

**Comment by DarknesGaming** [comment]
That is somewhat true. ROMs in the internet are compressed, but 7z and zip are often used compression standards. RAR isn't commonly used to compress ROMs anymore because they are a large size, and 7z can reduce the size to maybe below half.

**Comment by WilliamLCobb** [comment]
The problem with RAR is the only working library on iOS requires the framework to be embedded. This means it also has to be signed because it acts like a separate app. I can use the 921cbypass to dynamically load the app but it's only a temporary solution

**Comment by DarknesGaming** [comment]
Can't 7-zip extract what's inside RAR files? According to the official website, 7-zip can unpack RAR files, but can't pack anything in RAR format.

**Comment by DarknesGaming** [comment]
That explains why you have the UnrarKit framework. It also explains why there's a "NoRar" branch.

**Comment by mcat115** [comment]
I wanted support for it so I could play soul silver, but I used file hub so now I can. Does this mean that it won't return for a while? It would just make the process of getting roms easier.

**Comment by DarknesGaming** [comment]
I think 7-zip is supposed to be able to extract RAR files. I should go take a look at the problem and see what's wrong.
