### ISSUE TITLE
Question about GameCube on iOS

### ISSUE THREAD

**Issue by Fadi5555** [WilliamLCobb/iNDS#136]
Hi @WilliamLCobb l'm sorry I know this is the wrong place to write something like that.
First of all I want to thank you for your all works all are amazing.
actually I saw your video of running GameCube on iOS. You can't imagine how we feel about that.
This is our dream for long time to run it. Please make our dream come true. Again I'm sorry to write this here but all that because of my interest. Can this emu work only with jailbroken iOS or even with non jailbroken? If only jailbroken devices can you give me the repo to test it please.

Thanks for everything.

**Comment by DarknesGaming** [comment]
That would be awesome!

**Comment by Fadi5555** [comment]
Yeah you're alright.

**Comment by Anuskuss** [comment]
Btw, it will only stream the data to your device (like for example Nvidia GameStream).

**Comment by WilliamLCobb** [comment]
I'm going to finish iNDS 2.0 and fix as many bugs as possible and then start really working on getting gamecube on iOS. Right now it crashes at launch and there's a ton of work left to get it going

**Comment by Fadi5555** [comment]
@WilliamLCobb one question please.
Is GameCube emu will work on go or just streaming. I really hope to work on go like dolphin and iNDS

**Comment by WilliamLCobb** [comment]
Just got the GameCube to boot on the iPhone which is good progress. No picture yet though. Any ideas for a name? I would merge it back into Dolphin but I'm going to have to heavily modify the source to get it to work

**Comment by pmp174** [comment]
Remember iniidae?

**Comment by Vampire242** [comment]
@WilliamLCobb How about icube4ios for a name. And I know the question has already been asked but I'll ask again... Is GameCube emu  going to be streaming from a computer or will we be able to just launch it and select andiso or rom from our tablets and phone like in INDS

**Comment by WilliamLCobb** [comment]
I like iniidae. And there will be no streaming. It will play from your phone

**Comment by Fadi5555** [comment]
@WilliamLCobb please if you need any tester let me know.
About me I think it would be nice if you merge your work to Dolphin emu project. Because the dolphin emu is already done so so many things and bugs as well. Also you will find other people to help you more for iOS port of it. So that's why the merging your work to dolphin as an iOS port of that it would be nice and will have regularly update and fixing issues and bugs as well.

Again we all appreciate your amazing work. Keep going....

**Comment by Vampire242** [comment]
If he did it that way we wouldn't only a game cube emulator but also a wii that would be epic

**Comment by Vampire242** [comment]
@WilliamLCobb Question is would a wii even be possible to emulate on our devices?

**Comment by pmp174** [comment]
The wii and gamecube are the exact same. Dolphin emulates both so the only issue would be controlling the game.

**Comment by DarknesGaming** [comment]
Wow. Despite that this is a closed issue, we are still talking about this.
Does this issue have to be closed? A GameCube emulator would be great, and there's a whole bunch for iOS that won't install to my jailed phone.

**Comment by DarknesGaming** [comment]
@WilliamLCobb since you're finishing iNDS 2.0, would you like to test the upgrades I made in iNDS? It's already up to date with the master branch, so don't worry about fixing bugs or using cs_bypass.
Be sure to give feedback in that list of ideas I made for iNDS 2.0.0.

**Comment by Fadi5555** [comment]
I'm really hoping from @WilliamLCobb to start working on iOS port of dolphin. Because nds emu is already found on retroarch. So focusing on dolphin it would be amazing. Specially it gets a lot of bugs fixed and it goes well right now. Because of daily update. So if he could merge later his work to master. He will find a lot of people there who improve dolphin emu regularly. So step by step it gonna match android version so easy.
After that it will be like other project like ppsspp as well as retroarch. I mean for all platforms.

**Comment by WilliamLCobb** [comment]
I have been focusing on it and I have a working version on GitHub. We should move the discussion to there

**Comment by Fadi5555** [comment]
Ok
