### ISSUE TITLE
Save states do not work 

### ISSUE THREAD

**Issue by rmiller757** [WilliamLCobb/iNDS#137]
Running on iPhone 6 
Version 1.5
Build store 

Everytime I use a save state and open it back up, the game shows just a white screen and does not work.

**Comment by essiw** [comment]
try updating to the latest version via the buildstore and see if it persists :)

**Comment by DarknesGaming** [comment]
I tested this on iNDS 1.6.0. This problem is fixed already...

**Comment by rmiller757** [comment]
Thank you!

**Comment by barlss** [comment]
How do I get iNDS 1.6.0?
