### ISSUE TITLE
Weird noise on rom selection screen

### ISSUE THREAD

**Issue by peter961785** [WilliamLCobb/iNDS#138]
When launching the app the first screen where the roms are list, there is a strange repetitive noise in a periodic sequence. You can hear it better if you put the phone near your ear.
iOS 9.3.2 buildstore version 1.5.3 (no rar)

**Comment by WilliamLCobb** [comment]
This is used to detect the mute button. Since Apple disallowed apps to detect it, even though private APIs, we have to play a sound and see how long it took to actually play to determine if the mute button is on. I'll fix it to turn the volume off though so it's not audible
