### ISSUE TITLE
Remove "a" in app icon.

### ISSUE THREAD

**Issue by skyfliers** [WilliamLCobb/iNDS#14]

**Comment by pmp174** [comment]
You need to make sure your running the release version. The a is only there to symbolize debug/development versions . Go into the scheme menu and change to release where it says run.

**Comment by skyfliers** [comment]
Yeah I played around with the source a bit more and discovered that. Sorry!

**Comment by pmp174** [comment]
If anything or any questions the wiki might have some resources on building
