### ISSUE TITLE
iNDS Problem

### ISSUE THREAD

**Issue by DudeShadow** [WilliamLCobb/iNDS#154]
Hello
Currently I am using iPad Air 2 (64gb) with the latest iOS 9.3.2, not jail broken and the iNDS is the latest update. I have used the iNDS app and it worked phenomenally until after 8 hours of usage it crashed. Based on your requirements I have met it. After the crash I cannot access the app anymore. I downloaded the app from IEmulators.

Would like to find out if there is a problem
Regards

**Comment by essiw** [comment]
iEmulators have an out-dated app (1.4.0) which has a bug that causes a infinite crashloop.

**Comment by DudeShadow** [comment]
Any other site I can use to download the app that doesn't have this problem?

**Comment by essiw** [comment]
builds.io but that requires you to pay 10 euro's per year. Or you could try to build the app yourself (see the wiki at the top for instructions). I think it is in cydia as well if you have jailbroken your device.

**Comment by DudeShadow** [comment]
Thanks for the help
