### ISSUE TITLE
No sound

### ISSUE THREAD

**Issue by timosupje** [WilliamLCobb/iNDS#156]
I have no sounds in inds

**Comment by essiw** [comment]
You really have to put more information here, please read the read.me at https://github.com/WilliamLCobb/iNDS

and please look at other similar topics like this one https://github.com/WilliamLCobb/iNDS/issues/151 , and the ones mentioned in there.

**Comment by timosupje** [comment]
I play inds on ios 9.3.1 and i hve beatn black 2 fully but i never had sound, the app works fine

**Comment by timosupje** [comment]
I play on air 2 ios 9.3.1 and its unjailbreaked

**Comment by WilliamLCobb** [comment]
Apple makes controlling where sound comes out of very difficult. I've fixed it on my device and I'll release an update soon
