### ISSUE TITLE
Wireless linking

### ISSUE THREAD

**Issue by mcat115** [WilliamLCobb/iNDS#159]
Will wireless linking ever be added to iNDS so people can play games and trade with each other? Like what's in gba4ios. If so, any ballpark when it'll come out?

**Comment by WilliamLCobb** [comment]
DeSmuME does not support wireless connections and don't plan too. Wireless support will probably never happen

**Comment by DarkLegend481** [comment]
An older version of DeSmuME can use wireless, but with WinPcap... I used it and traded so much Pokémon...
