### ISSUE TITLE
Add support for icade controllers/controller issues 

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#17]
The emulator would benefit from supporting Bluetooth controllers since it would make space for the two screens and also make game play more responsive

**Comment by OkazakiTheOtaku** [comment]
MFi controllers do work, and it was stated that support for the two screens would be improved with issue #7

**Comment by pmp174** [comment]
Lets keep this open for icade implementation then. I can help test it since I was stupid enough to buy an Icade controller .

**Comment by pmp174** [comment]
https://github.com/jiaxianhua/nds4ios/commit/fbb73a19fbf425b714f4c8ee8ae79acbb7259d65

**Comment by pmp174** [comment]
I've begun adding code for Icade into my own fork so that I can later merge it into this project. I am however having some trouble with code/syntax ( I suck at programming ). anyways I will keep on trying to get it to work . If anyone can help the branch is https://github.com/pmp174/iNDS . Once I get Icade working I will open a pull request .

**Comment by pmp174** [comment]
im almost done getting icade to work on my fork.https://github.com/pmp174/iNDS

**Comment by pmp174** [comment]
Fixed for the most part
