### ISSUE TITLE
Add support for "open in" .nds extension

### ISSUE THREAD

**Issue by asc6** [WilliamLCobb/iNDS#18]
At first I thought I was losing my mind because trying to share the file to iNDS wasn't available but many other apps were. I then realized that it has to be a .ZIP file for iNDS to pick it up and offer to accept the file. Any chance we can add the .nds extension as well? Thanks!

**Comment by WilliamLCobb** [comment]
Weird. It "should" support .nds. Thanks for letting me know I'll make sure to fix that in the next version.

**Comment by pmp174** [comment]
I believe he is talking about the open in.. Option

**Comment by WilliamLCobb** [comment]
Still working on this. iOS doesn't make associating random extensions easy and everything I've read on it hasn't worked so far.

**Comment by OkazakiTheOtaku** [comment]
A good work around until it's fixed (which I personally use) is get the free "Documents by Readdle" app which accepts any file input and let's you ZIP them. Then you just export the ZIP to iNDS.

**Comment by asc6** [comment]
Personally, I use dropbox and so it's easy to keep them all zipped. I was just trying to keep them all in just the file so I could send them to someone not so techy and iOS would automatically figure out what goes in GBA4iOS and what goes to iNDS. A zip file offers both. 
Not a super big deal and I appreciate you looking into it.

**Comment by WilliamLCobb** [comment]
Will be fixed in 1.3.0
