### ISSUE TITLE
jailbreak to unjailbreak

### ISSUE THREAD

**Issue by timosupje** [WilliamLCobb/iNDS#187]
if you jailbreak and download the app and then remove the jailbreak will it then still be usable?

**Comment by josevieirame** [comment]
No, it dont!

**Comment by DarknesGaming** [comment]
If you downloaded iNDS from Cydia, re-jailbreak your phone if you want iNDS to work again.
If you got iNDS from iEmulators or another website, and the certificate was revoked, please wait until another certificate is created.
If you built iNDS from Xcode, and iNDS won't launch, your certificate got revoked. As an Apple Developer, I have edited the wiki to guide you with instructions that are explicit (or specific, to those who do not understand more advanced vocabulary). Please click the wiki tab, or [here](https://github.com/WilliamLCobb/iNDS/wiki) to find the instructions.
