### ISSUE TITLE
iNDS Crashes in 5 seconds entering the game

### ISSUE THREAD

**Issue by Squirtoles** [WilliamLCobb/iNDS#19]
My iNDS crashes every 5 seconds in to any pokemon game, and other games it crashes when I open it. I have a iPhone 5C, IOS 9.0.2

**Comment by Squirtoles** [comment]
Also I get this cydia error message when I download the source but I can still use the emulator (if it matters)

**Comment by brujo5** [comment]
Try to enable audiosync

**Comment by WilliamLCobb** [comment]
It was caused by a combination of an optimization option I enabled a few builds ago and upgrading to Xcode 7.2. It should be fixed now.

**Comment by brujo5** [comment]
ARM32 bits iphone 5 and below, They do not have enough power to run the emulator.

The interpreter mode is CPU intensive

**Comment by brujo5** [comment]
The only problem I experienced Is that some games need audio sync enabled or crashes at certain point or when there is a lot of movement on the screen

**Comment by Squirtoles** [comment]
Thank you, it seems to work now perfectly, besides how slow my phone is :)

**Comment by mk8itra1n** [comment]
You should get the iPhone 6s Plus. That processor is even way more powerful than my iPhone 6 Plus. And it has double the RAM than mine 2 GB
