### ISSUE TITLE
AudioSync OFF cause crash in game, is this normal??

### ISSUE THREAD

**Issue by brujo5** [WilliamLCobb/iNDS#20]
HI, audiosync off cause crash after few time of gameplay, is this normal?

tested few games like new super mario bros, dragon ball z attack of saiyan, etc. but i think happend in all games.
I prefer to play with audio sync disabled because It makes the sound heard clearly.

Audio sync enabled work fine (games never crash) but It makes the sound awful.

tested in iphone 6S/iphone 5S jalibroken ios 9.0.2

**Comment by pmp174** [comment]
The weird thing is I had the opposite happen to me. When I turned it on the app began crashing in certain games

Ipasd air2 non-jailbroken  9.2.1

**Comment by brujo5** [comment]
@WilliamLCobb 

found some info interesting.

if i installed inds via cydia (sistem application) audio sync cause crash BUT if i installed inds as ipa audio sync not caused crash

tested few times, weird You have any idea?

**Comment by WilliamLCobb** [comment]
Wow that is really weird. I can't think of any reason for it but I'll do some tests and try to fix it.

**Comment by WilliamLCobb** [comment]
Should be fixed now. I haven't had any problems with audio sync on or off
