### ISSUE TITLE
The message banners distract game play on the ipad

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#21]
For some reason the message banners in the app are always in portrait even when in landscape. This makes the game play experience distracting on the ipad since the banners constantly show up. It would be nice to have the option of turning the banners off or for the banners to conform to the iPads orientation in order to be put in a less distracting position.
Ipad air 2 
non-jailbroken 
iOS 9.2.1(beta)
![image](https://cloud.githubusercontent.com/assets/15956420/11914772/5dc30172-a656-11e5-8e55-f3cf925908d9.png) ( don't judge for the game I'm playing # kid at heart)

**Comment by WilliamLCobb** [comment]
Yea that's definitely not intended. I think I'l going to add a syncing icon to the table rows and remove the ugly bar all together.

**Comment by pmp174** [comment]
Yes that would be much better😊
