### ISSUE TITLE
No select and start buttons on MFI controller

### ISSUE THREAD

**Issue by illando** [WilliamLCobb/iNDS#22]
There aren't no no select and start buttons assigned on MFI controller. My suggestion is to assign them to L1 and L2.
It could also be great to assign the iNDS menu menu boutton to the main button on the MFI controller ( in some models it's called Pause).

My configuration:
iOS 9.1, No jailbreak, MOGA rebel.

Thanks!

**Comment by pmp174** [comment]
#17 there is an issue open about controllers.

**Comment by WilliamLCobb** [comment]
Controller settings will be coming soon allowing you to optionally hide and show touch screen buttons as well as map your own buttons.

**Comment by illando** [comment]
An interface for custom controller setting will be the best option for sure, but in the meantime could you just map a default basic setting for select and start buttons on L1 and L2?
It' very annoying to disconnect and reconnect the MFI controlled  every time we need to press pause on some games!

**Comment by WilliamLCobb** [comment]
I can. Do no mifi controllers have start and stop buttons? I could just leave hose buttons on screen

**Comment by illando** [comment]
I think that all the MFI have the Pause/Menu button on the frontside as you can check here:
https://afterpad.com/mficontrollers/
and all of them (excluding the old and bad Logitech PowerShell) have the L2 and L1 buttons.
I think there's no need to left any buttons on screen.
My suggestion is to like other emulators like GBA4iOs or Provenance are doing assigning:
Select -> L1
Start -> L2
iNds option -> MFI Pause/Menu

Thanks.

**Comment by Anuskuss** [comment]
My suggestion:
L2 -> Select
R2 -> Start
Menu -> iNDS menu

Same configuration as in PPSSPP.

**Comment by pmp174** [comment]
Can't this be based on profile where a person can choose individually what each button does?

**Comment by illando** [comment]
@pmp174 I think that's the initial idea of @WilliamLCobb, but meanwhile I was trying to propose a simpler default configuration. :smile:

**Comment by illando** [comment]
@WilliamLCobb I see you are working again on the project. Can you find some time to fix this simple problem please? Thanks again in advance.

**Comment by WilliamLCobb** [comment]
Yea I'll need some people to help me test it because I haven't gotten my hands on a controller. I'll post here when I start

**Comment by illando** [comment]
@WilliamLCobb Great! Thanks!

**Comment by essiw** [comment]
@WilliamLCobb I was wondering if you could please unhide the buttons until this problem is fixed :) I own such a controller and some games are not playable with such a controller because the start and select button are missing. Just unhiding the buttons until would at least make them playable with the controller again :) And I suppose it wouldn't take that much time to change this as a temporary fix. Thanks

**Comment by WilliamLCobb** [comment]
Start and select should no longer hide when the controller is plugged in. Button remapping is on my todo list

**Comment by chefff** [comment]
does anyone here have expiernce in using the playsation 3 controller bluetooth as a controller? or does it have to be strictly be an MFi controller cuz i erwally want to use a controller to play iNDS
