### ISSUE TITLE
Play online in iNDS

### ISSUE THREAD

**Issue by SamuB162** [WilliamLCobb/iNDS#229]
Hi, I am playing pokémon Platinum on iNDS (via Buidstore) on my iPhone 6. I wanted to evolve pokémon that evolve via trading, but that doesn't seem possible. Is there any way to do this? 
I've looked for trade evolution patched roms, I found a rom that worked, but I still don't know how to transfer my data to that game, if i'st even possible.

**Comment by WilliamLCobb** [comment]
Possibly in the future. It looks like MelonDS may finally crack NDS wifi and if so I'll add it

**Comment by SamuB162** [comment]
Ah ok, thans doe answering!



On Aug 16, 2017 at 8:10 PM, <Will Cobb<mailto:notifications@github.com>> wrote:


Possibly in the future. It looks like MelonDS may finally crack NDS wifi and if so I'll add it
