### ISSUE TITLE
Compile Failed

### ISSUE THREAD

**Issue by DevSplash** [WilliamLCobb/iNDS#232]
https://github.com/WilliamLCobb/iNDS/commit/34cdabf16794801028e31d2cda4aba0b488fffd3

**System:** 
Mac OS 10.11.6

**Xcode Version:** 
8.2

**Log:** 
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_URKArchive", referenced from:
      objc-class-ref in iNDSCheatsTableViewController.o
      objc-class-ref in AppDelegate.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by eosol** [comment]
You just need to update the 'UnrarKit.framework', a guide can be found here:

https://github.com/abbeycode/UnrarKit

**Comment by Cynfelyn** [comment]
I tried updating Unrarkit.framework and while the build no longer fails, the app now fails to be installed (at least when using the iOS simulator in Xcode).

Why could this be?

**Comment by eosol** [comment]
Semi-educated guess would be you can't run an emulator within an emulator (the iOS simulator), try loading it onto your iDevice.

**Comment by Cynfelyn** [comment]
When I do that though, the original error comes up again, as if I never updated Unrarkit.framework - this happens only when attempting to run iNDS directly on the device. When attempting to run it in a simulator, that particular error doesn't come up.

**Comment by eosol** [comment]
Sorry man, can't help you there, updating UnrarKit in my project is what did it for me.

**Comment by BlueSplash** [comment]
It worked when I updated UnrarKit.

**Comment by Cynfelyn** [comment]
Perhaps I'm updating UnrarKit incorrectly. 

I ran UnrarKit iOS, then took the Unrarkit.framework that was created in Products, and put it in the iNDS folder (replacing the old one). I also removed the old unrarkit.framework and added in the new one.

Am I missing something?
