### ISSUE TITLE
Ipad issues

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#24]
Issue with onscreen controls on non-jailbroken iPad air 2

![image](https://cloud.githubusercontent.com/assets/15956420/12009061/1f7a702c-ac36-11e5-8a46-cc657ab6e52d.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12009062/1fbe3eb0-ac36-11e5-8bfd-5e72deca306d.png)

**Comment by WilliamLCobb** [comment]
Is it still happening?

**Comment by pmp174** [comment]
This was before I realized the screens could be moved. This is why I told you to change the iPads default.

**Comment by WilliamLCobb** [comment]
Oh okay. That's not what he default is meant to look like though. It seems like it got landscape and portrait mixed up

**Comment by pmp174** [comment]
I was able to fix it by moving the buttons and screens.

**Comment by pmp174** [comment]
One issue you might want to address is missing buttons the layout has the button somewhere else on the screen and your not able to move it since its not on the screen . I can't find the r or the xyab buttons.
![image](https://cloud.githubusercontent.com/assets/15956420/12011927/17659b66-acb1-11e5-82f3-d5588082d354.png)

**Comment by OkazakiTheOtaku** [comment]
This happens to me on my 6s+ when I start the first ROM of the app launch in landscape mode. If I start in portrait, it's fine. I don't know if this is helpful, but I figured I'd contribute what I have.

**Comment by pmp174** [comment]
I know I think he needs to set a default position for each screen size in landscape and portrait
