### ISSUE TITLE
Note of performance

### ISSUE THREAD

**Issue by OkazakiTheOtaku** [WilliamLCobb/iNDS#25]
This isn't really an "issue" but there's no general discussion place so...
Anyway, up until yesterday I've been running on an iPhone 5s, and most games lag, but now I have a 6s+ and without JIT I haven't found a single game that doesn't run at 60fps. Even high polygon games like M64DS or MKDS. It's pretty much smooth sailing all the way through.

I know that not everyone has a 6s series phone (far from it) but I would like to note that on those devices it's not as much a priority as it works flawlessly.

**Comment by WilliamLCobb** [comment]
Yep, iPhone 6 and up run almost at a constant full speed. The only real benefit of JIT would be improved battery life and a fun challenge to develop. I'm still looking for other ways to increase performance on older devices though without having to mess with JIT.

**Comment by pmp174** [comment]
This version seems to have improved a lot of issues. While crashing is still an issue. I was able to get 12 stars in mario 64 ds . The app still crashes but before the game would crash so much I was only able to get 2 stars. The game is finally somewhat playable. It does still need work but seems to be getting more polished with every version. Keep up the good work.

**Comment by pmp174** [comment]
This latest version is really really good. I don't know what you did but I've been playing for an hour and have not experienced any crashes.

**Comment by WilliamLCobb** [comment]
Yea I fixed a bug in the core that was causing 90% of crashes. Hopefully it will stay that way.

**Comment by pmp174** [comment]
In two months you managed to do what the NDS4IOS and Nitrogen devs couldn't do, make this emulator run like butter. I finally finished super mario 64 something I thought I was never going to do using the emulator.
![image](https://cloud.githubusercontent.com/assets/15956420/12062296/dae1757a-af67-11e5-80ff-4417c74b9aab.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12062297/dae8d496-af67-11e5-9045-969529babafa.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12062298/daeb66d4-af67-11e5-92cb-4cc4b6b868f7.png)

**Comment by WilliamLCobb** [comment]
Holy shit thats amazing. No problem man thank you so much too. You've helped so much throughout the development by creating the wiki and finding bugs and supporting iCade. Hopefully we can make this the best emulator on iOS

**Comment by OkazakiTheOtaku** [comment]
I have no doubt this will be the best emulator on iOS pretty soon. It's just...so good. And you actually listen to our requests. It's amazing. Thank you.

**Comment by pmp174** [comment]
Anybody got good games to recommend I finished mario 64 and bros. I need more.

**Comment by WilliamLCobb** [comment]
The Zelda games are fun but a lack of microphone support makes them pretty hard to beat. Mario & Luigi: Bowsers story is pretty fun as well as the Pokemon games. Also warrio ware touch is really fun if you've never beaten it
