### ISSUE TITLE
Top Screen Only AirPlay Mirroring

### ISSUE THREAD

**Issue by Byron657** [WilliamLCobb/iNDS#26]
I remember this a nds4ios feature, the top screen mirrored, while the bottom screen was on the phone. When I try to reach this, I just get yellow screen.

**Comment by pmp174** [comment]
A tv os version is being worked on but this is also a possibility especially for the older apple tvs

**Comment by Byron657** [comment]
Will it work using AirPlay programs like Reflector 2, or only Apple TVs?

**Comment by pmp174** [comment]
The tv os version will only work on the apple tv. But if airplay is added it would be able to work on those programs.

**Comment by Byron657** [comment]
Okay, really thanks for the clarification :)

**Comment by WilliamLCobb** [comment]
Thats a result of the new layout manager. How are you mirroring the display? Maybe I can test it and fix it.

**Comment by pmp174** [comment]
Ive been looking into this. I played mario straight from a save state onto the tv and the top screen showed up while the bottom didn't. When I started it normally it showed the entire screen. I might upload a video to show what exactly happens.

**Comment by WilliamLCobb** [comment]
What are you using for mirroring? AirServer?

**Comment by pmp174** [comment]
This is the result I got
When airplay is on the image on the tv is the top screen in an ugly orange un centered letterbox.
When the app is opened and airplay is turned on the entire screen is mirrored .
http://youtu.be/R_ogFa0ruFI

**Comment by pmp174** [comment]
I used an apple tv to mirror the image

**Comment by pmp174** [comment]
Ill see if I can test airserver

**Comment by pmp174** [comment]
This is the Result I got from airserver and its identical to what I got on my apple tv. http://youtu.be/eZbpml34BRE

**Comment by WilliamLCobb** [comment]
Ahh thanks for the video I know the problem. I'll get the AirServer free trial tomorrow and fix it.

**Comment by pmp174** [comment]
Alright perfect

**Comment by Byron657** [comment]
Using Reflector 2 (http://www.airsquirrels.com/reflector/) now with iNDS 1.2.1 it mirrors the app, but the entire app! I remember back in nds4ios that the top screen was mirrored in the airplay server in landscape full screen, while the phone's screen had only the bottom screen (the nds touchscreen). That was so good! :D Now it can be achieved only using TvOS so?

**Comment by pmp174** [comment]
The tv os app still hasn't been made but it will be in development. He is working on a fix for the issues so that it shows only the top screen

**Comment by WilliamLCobb** [comment]
This should be mostly fixed in 914cbc2. You can create a profile to expand the touch screen to be full screen. 

Editing the layout while air playing acts really weird though.

**Comment by WilliamLCobb** [comment]
Should be perfect now. Let me know if anything else needs fixing
