### ISSUE TITLE
No download?!?!

### ISSUE THREAD

**Issue by GamerX0307** [WilliamLCobb/iNDS#27]
When ever games I try to download get to 100%, the app freezes, and when I exit and then open up INDS, the rom I tried to download disappeared. Plz help me.

**Comment by pmp174** [comment]
Until the issue is fixed you can use an alternate method found here.https://github.com/WilliamLCobb/iNDS/wiki/Importing-Roms

**Comment by WilliamLCobb** [comment]
What device are you on? The app will freeze if you're running on a slow device because it's busy extracting the file. It should eventually complete and show the game in. I can move the extraction to a background thread though to prevent the freezing issue.

**Comment by GamerX0307** [comment]
I'm on IOS

**Comment by GamerX0307** [comment]
8.4

**Comment by GamerX0307** [comment]
IPad Mini

**Comment by pmp174** [comment]
Something that could be causing issues is ios 8.4 . I recommend updating to ios 9 . I believe there is a jailbreak for 9.0.2 if you could get it signed somehow. You could also sideload this app on a non-jailbroken device. The original ipad mini also has a weak a5 processor which could be an issue. Lastly I believe he actually fixed the issue and you just need to update to the latest app version.

**Comment by WilliamLCobb** [comment]
Should be fixed in 1.3.3
