### ISSUE TITLE
8bitdo controller problem

### ISSUE THREAD

**Issue by ghost** [WilliamLCobb/iNDS#280]
I am using 8bitdo zero 2 controller

i tried using the icade mode (A + Start), almost all the buttons not working. i believe the controller turned into dualshock 4 to connect to iphone. so the buttons all wrong. can you add feature to remap the all the buttons (just like delta emulator)?

i tried using the keyboard mode (R + Start). i played gba emulator on my iphone using Delta emulator. can you add a keyboard support for iNDS and ability to remap the buttons? that would solve all the problems.

Sorry if my english are bad.

**Comment by CrafterPika** [comment]
Please close this issue this is the old repo, New repo is here https://github.com/iNDS-Team/iNDS
