### ISSUE TITLE
Layout profile issue 

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#31]
When I try to delete a layout profile it doesn't delete. The profile appears to leave the menu but it comes back when I look at the settings. Also it would be a good idea to add a check mark next to the profile so that you know which one you are using. I think it might have to do with the fact I named the profile default in order to test it.

**Comment by brujo5** [comment]
@WilliamLCobb 

![image](https://cloud.githubusercontent.com/assets/4172898/12021229/d71f81e8-ad41-11e5-9258-fae88ee1f66c.png)

This is the max i can enlarge the screen, is normal?

Iphone 6S / iphone 5S

**Comment by WilliamLCobb** [comment]
No but it's fixed in the latest source

**Comment by brujo5** [comment]
The layout Enlarger Or the layout profile?

The answer was for me or the creator of the post?

**Comment by pmp174** [comment]
![image](https://cloud.githubusercontent.com/assets/15956420/12021505/4ed70306-ad55-11e5-8d4c-5684f88dc436.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021506/4edf10d2-ad55-11e5-8503-60cbf50f90f9.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021507/4edf405c-ad55-11e5-9a99-7af099c2b58b.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021508/4edf89c2-ad55-11e5-9707-f79046c8c17f.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021509/4ee1f86a-ad55-11e5-95ab-b1b139a59a8a.png)

**Comment by pmp174** [comment]
![image](https://cloud.githubusercontent.com/assets/15956420/12021520/65db71c2-ad55-11e5-9ab6-7b6aa7feb6c0.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021521/65e86be8-ad55-11e5-9b0a-451579d564bb.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021522/65e8962c-ad55-11e5-92d1-f7f4f883235d.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021523/65ebaa92-ad55-11e5-8ae9-83b003b4567b.png)
![image](https://cloud.githubusercontent.com/assets/15956420/12021524/65ec9a42-ad55-11e5-9c97-41e03ff630dd.png)

**Comment by pmp174** [comment]
I delete the profile 
And it comes back

**Comment by WilliamLCobb** [comment]
Sorry I just woke up haha. That was meant for Brujo in issue 33. I'll fix this issue today.

**Comment by brujo5** [comment]
Ok. Close layout enlarger issue. 

Can expect an update later today? Thx

**Comment by pmp174** [comment]
😂 it's alright I was getting confused

**Comment by brujo5** [comment]
It was my fault, sorry guys:)

**Comment by pmp174** [comment]
heres the issue in a screen recording.  https://youtu.be/RH6XYJe7X14

**Comment by WilliamLCobb** [comment]
Is it only when you delete a profile named default?

**Comment by pmp174** [comment]
I think so let me check

**Comment by pmp174** [comment]
Yes

**Comment by brujo5** [comment]
@pmp174 

Do you have an ipa with the latest changes?

I would like to enlarge the screen a little more but recent changes still are not in cydia version.

**Comment by pmp174** [comment]
I could possibly send you a signed version but I'd have to figure it out 😂

**Comment by pmp174** [comment]
I will need your email to send you the ipa

**Comment by brujo5** [comment]
Sure. 

twinaphexretro@gmail.com

Thank you.

**Comment by pmp174** [comment]
![screen shot 90](https://cloud.githubusercontent.com/assets/15956420/12037832/8797176e-ae20-11e5-80ff-77c8edb83843.png)


I apologize but there seems to be an issue with his code since it is having these errors and won't build. @WilliamLCobb will have to fix it .

**Comment by WilliamLCobb** [comment]
Make sure the target is not the iPhone simulator

**Comment by pmp174** [comment]
ok

**Comment by pmp174** [comment]
@brujo5 once its built I will send the IPA

**Comment by brujo5** [comment]
Ok thanks

**Comment by pmp174** [comment]
![screen shot 91](https://cloud.githubusercontent.com/assets/15956420/12038020/79e39fc8-ae22-11e5-8544-84d22db68b4d.png)
unfortunately apple likes making money more than supporting devs. I don't have a payed dev account so I cant make an IPA. I tried many terminal commands but non of them seem to work. 😞

**Comment by pmp174** [comment]
i got it working

**Comment by pmp174** [comment]
@brujo5 I have sent the IPA to your email

**Comment by brujo5** [comment]
Installed, thanks for the help.

**Comment by pmp174** [comment]
@brujo5 ill send the new IPA soon

**Comment by brujo5** [comment]
Thanks you.

**Comment by WilliamLCobb** [comment]
This should be fixed in 1.3.0 and on

**Comment by pmp174** [comment]
This issue still hasn't been fixed

**Comment by WilliamLCobb** [comment]
Still Default?

**Comment by pmp174** [comment]
Yes
