### ISSUE TITLE
No iNDS App in "Open in..." ?

### ISSUE THREAD

**Issue by samluxh** [WilliamLCobb/iNDS#32]
If I want to import ROMS through Safari and let Safari download it and tap on "Open in..." there is no iNDS app?

Thank you!

**Comment by WilliamLCobb** [comment]
What's the extension? .nds?

**Comment by samluxh** [comment]
.rar

**Comment by WilliamLCobb** [comment]
Will be fixed in next version (1.3.0)

**Comment by samluxh** [comment]
Is it possible to implement the feature to be able to import ROMS within iTunes?

So to choose iNDS on the iPhone in iTunes and push the ROMS in the box on the right side...

:+1:

**Comment by pmp174** [comment]
That would be a share sheet try to open an issue for that
