### ISSUE TITLE
cheat suppor for complex codes 

### ISSUE THREAD

**Issue by eddiebrook** [WilliamLCobb/iNDS#34]
here an example http://www.gamefaqs.com/boards/959019-the-legend-of-zelda-spirit-tracks/52693517

the legend of zelda spirit tracks

Fake Mic Blow (L Button)
94000130 FDFF0000
220B5308 0000005F
D2000000 00000000

Fake Mic Blow (R Button)
94000130 FEFF0000
220B5308 0000005F
D2000000 00000000

any idea if this codes will work?

**Comment by pmp174** [comment]
Cheat implementation is being worked on. https://mobile.twitter.com/iNDSapp/media .I'm not sure if it will support those codes but it's possible.

**Comment by eddiebrook** [comment]
These codes help us to play games that require microphone.

Hope the developer confirm this possibility.

**Comment by pmp174** [comment]
The developer is actually also working on microphone implementation yo should check issue #23

**Comment by eddiebrook** [comment]
yeah both implementation will be great for sure.

**Comment by WilliamLCobb** [comment]
All AR codes should work. I can the ones you posted later. I've compiled a database of 160,000 cheats so if you need one it should be included in the next version of iNDS.

**Comment by brujo5** [comment]
to replace the microphone using a cheat code will be the best.

I've waited long to start and finish Zelda games. many users will be grateful

**Comment by pmp174** [comment]
@brujo5 it would be better to use the actual mic on the iOS device because some games actually make use of recording a persons voice.

**Comment by brujo5** [comment]
what I mean is that a quick way to do it, while the microphone implementation is finished.

**Comment by pmp174** [comment]
I agree .

**Comment by pmp174** [comment]
![screen shot 93](https://cloud.githubusercontent.com/assets/15956420/12056014/8798efc2-af00-11e5-9161-ed983707591f.png)

**Comment by WilliamLCobb** [comment]
Fixed

**Comment by WilliamLCobb** [comment]
I'm still adding an interface to put in your own cheats but the cheat db I got is working now

**Comment by brujo5** [comment]
Great news, Hopefully I can run the mic ne using cheats Posted by @ eddiebrok

**Comment by pmp174** [comment]
@brujo5 I sent the latest IPA to you 😊

**Comment by brujo5** [comment]
Installed, thank you:)

**Comment by brujo5** [comment]
@WilliamLCobb 
@pmp174 
@eddiebrook 

Hey guys finally got working fake blow (L Button) using the cheat above.

Tested in zelda spirit tracks usa version


![image](https://cloud.githubusercontent.com/assets/4172898/12067644/c2cb4292-afba-11e5-858d-f4375fb48f6d.png)

Max rupes + fake blow

![image](https://cloud.githubusercontent.com/assets/4172898/12067651/daa84842-afba-11e5-8904-e90a43f0468a.png)

The bad new is that zelda phantom hourglas need microphone support!!

I do not remember where in the game you have to say hello or make some noise

**Comment by pmp174** [comment]
Yes that will be the next addition to this emulator, hopefully it won't be too difficult to add microphone support but it will make the experience much better.

**Comment by WilliamLCobb** [comment]
Awesome! I'm glad it worked. DeSmuME can play pre recorded audio files so I think I can use that to enable the microphone in the next version

**Comment by brujo5** [comment]
Thank you all.

**Comment by STLITGuy** [comment]
I used this wav in DeSmuME for Hourglass and it worked great to get past all the times where the mic is needed.  I'd love not to have to play on the computer just to get past certain spots.

http://www.mediafire.com/download/teowvwr2h2y3nvc/Zeldanoise095.wav

**Comment by brujo5** [comment]
Thank you.

Hope the feature will be implement soon!!

**Comment by Pepperoony** [comment]
I tried imputing the code into iNDS but it's simply not working, any suggestions? I know for sure its on and I'm clicking the L button when I need to blow

**Comment by brujo5** [comment]
@Pepperoony 

Only work in the US version.

**Comment by Pepperoony** [comment]
@brujo thanks for the help, but it didn't seem to do much. I turned the cheat off, started the game normally without it on, and then turned it on and fast forwarded to my save and clicking L when trying to perform a song did nothing, this has to be an error or something

**Comment by brujo5** [comment]
here my cheat https://www.sendspace.com/file/ocf3g2

Put the same name as your rom

**Comment by Pepperoony** [comment]
@Brujo5 not entirely sure what I was supposed to do with that file.

**Comment by maros99** [comment]
I'VE MADE IT!!!
I just overstepped the candle thing into the temple of fire!! Using the 3x speed cheat, is simple. I've tried many times to run into the left wall until I overstepped it and fell on the bottom-left platform. If you want I can upload the .svg file
