### ISSUE TITLE
Joystick (analog) control 

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#35]
This is no where near an urgent issue but the joystick function is really poor and doesn't do the best job. Given it is a touch screen but I've seen some games that implement joysticks very well and possibly this control could be improved on. I know another issue is ds games aren't really designed for joysticks but this could be helpful especially in 3d games.

**Comment by WilliamLCobb** [comment]
Yea it's pretty terrible but I've been working on it. I've noticed if you touch outside the joystick it gets stuck moving one direction.

**Comment by pmp174** [comment]
Yes that's exactly what I've experienced

**Comment by pmp174** [comment]
https://github.com/Squarific/Touchscreen-Joystick
https://github.com/kazmiekr/joysticknode
I figured maybe these projects could help

**Comment by WilliamLCobb** [comment]
Thanks, I fixed it. It still gives me huge fps spikes when I use it though so I'll leave this open

**Comment by pmp174** [comment]
Ok but goood 😊

**Comment by WilliamLCobb** [comment]
Should work without too much fps drop now
