### ISSUE TITLE
Cheats never finish loading

### ISSUE THREAD

**Issue by brujo5** [WilliamLCobb/iNDS#38]
Cheats never finish loading. 6 min still nothing:(

Tested new super mario

Tested in iphone 6
![image](https://cloud.githubusercontent.com/assets/4172898/12041102/973bb9d0-ae2b-11e5-9b8c-637a720ff4fb.png)

**Comment by pmp174** [comment]
I was also having that issue. I think there is an issue extracting the file.

**Comment by brujo5** [comment]
with the desire I had to try them

**Comment by brujo5** [comment]
Extracted the archive cheats.rar but stll nothing

Drastic ds emulator for android use an file called usrcheat

**Comment by WilliamLCobb** [comment]
Oh sorry that code wasn't meant to be there yet it's not finished.

**Comment by brujo5** [comment]
Thanks for notifying us.
