### ISSUE TITLE
[Request] Add a Close Emulation or Exit emulation button

### ISSUE THREAD

**Issue by brujo5** [WilliamLCobb/iNDS#39]
as the title says,it would be great.

Happy New Year to all!!

**Comment by pmp174** [comment]
I was going to say the same thing to go back to the app start screen. I believe he didn't add it since it already lets you access everything from the smaller menu.

**Comment by WilliamLCobb** [comment]
I added an option for settings to open full screen.

**Comment by brujo5** [comment]
I meant a button to close the emulation and return to the menu for open another game just like ppsspp, retroarch

**Comment by pmp174** [comment]
Ohh god not the ppsspp and retrach menus 😫😫😫😫😫😫😫😫😫😫😫😫. Those interfaces are crap and difficult 😫😫😫😫😫😫😫.  Just a way to get back to the menu right?

**Comment by WilliamLCobb** [comment]
Yea I left that out because it felt kind of redundant. You can change the from the in game settings menu

**Comment by brujo5** [comment]
@pmp174 yeah your right.

@WilliamLCobb 

this perfect so anyway

**Comment by pmp174** [comment]
@brujo5 did you receive the IPA
