### ISSUE TITLE
Missing (script?) file

### ISSUE THREAD

**Issue by DylanTackoor** [WilliamLCobb/iNDS#4]
iPad Air 2, 64 GB, iOS 9.1, Non-jailbroken.

App won't compile because of this, make of it what you will. 

```
/Users/dylantackoor/Library/Developer/Xcode/DerivedData/iNDS-cckcvahlrrmlcjcnmdjnxqiutssq/Build/Intermediates/iNDS.build/Debug-iphoneos/iNDS.build/Script-28CC0BE7178E46D200AE77C2.sh: line 4: /Volumes/1: No such file or directory
```

**Comment by WilliamLCobb** [comment]
Might be fixed by installing git if you haven't or Xcode command line tools. You could also just delete the script by going to the project view in Xcode, selecting the iNDS target, going to Build Phases and deleting the script under the Run Script tab

**Comment by pmp174** [comment]
You should try redownloading the source. This is not an app issue. It seems to be a missing script thats not on your computer. You can also try downloading the file directly from github (https://github.com/WilliamLCobb/iNDS/archive/master.zip)  after you download it put it into the user folder and retry using the instructions on the wiki ( https://github.com/WilliamLCobb/iNDS/wiki/Building-INDS)

**Comment by DylanTackoor** [comment]
Sorry for the late reply, William's response helped me get it working. Thanks!
