### ISSUE TITLE
Questions and FAQ

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#40]
I'm going to open up this issue just for people who may have questions but don't think it's important enough to open an issue.

**Comment by pmp174** [comment]
My first question 😂 

I saw on the to do list you put making volume buttons bumpers which is awesome but would that be possible without a jailbreak?

**Comment by WilliamLCobb** [comment]
Suprisingly it is. You can do a ton of shady stuff with objective-c without a jailbreak, apple will just reject your app. Luckily, we don't have that problem haha

**Comment by pmp174** [comment]
Yay!!!!!!!
