### ISSUE TITLE
No option to allow external audio

### ISSUE THREAD

**Issue by Rapsac11** [WilliamLCobb/iNDS#41]
Hi there. 

Love the work being done on this emulator, being able to resize controls and layout is fantastic. Wanted to ask if there was plans to allow the app to run with audio from another app (say safari) to run while using iNDS? 

I know GBA4iOS had this option. Perhaps it could be adopted?

Thanks and keep up the good work!

**Comment by pmp174** [comment]
This is actually on his todo list in the app so yes this is most likely going to be implemented.

**Comment by WilliamLCobb** [comment]
Added in 1.4.1
