### ISSUE TITLE
[Request] hide/unhide controls overlays in real time

### ISSUE THREAD

**Issue by brujo5** [WilliamLCobb/iNDS#45]
as the title says, because some games can be played for touching screen only. 
Or hide/unhide in real time when is not nesesary.

**Comment by pmp174** [comment]
You could work around this simply by changing the opacity

**Comment by WilliamLCobb** [comment]
I'll add this

**Comment by brujo5** [comment]
@pmp174 
useless because it will still be there.  if I touch a button or dpad do something that I do not.

@WilliamLCobb 

Thanks, will be more aesthetic

**Comment by WilliamLCobb** [comment]
Setting opacity to 0 in 1.5.1 will disable controls
