### ISSUE TITLE
Audio does not play while ringer is muted.

### ISSUE THREAD

**Issue by MistieKitteh** [WilliamLCobb/iNDS#49]
iOS Devices: iPhone 6 and iPad Air 2
iOS Version: iOS 9.2
Jailbreak Status: No Jailbreak
Downloaded From: Github
Version:1.3.2

Could an "ignore mute" switch be added? Because I'd very much enjoy playing pokemon with Audio without having to put up with annoying "DING" sounds from iMessages. (I do not want to turn down my ringer either, so don't tell me to do that.)

**Comment by WilliamLCobb** [comment]
Yea I'll try and add that

**Comment by WilliamLCobb** [comment]
Added option in 1.4.1
