### ISSUE TITLE
Game emulation issue

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#5]
IPad air 2
Ios 9.2(beta 4)
Non-jailbroken 
Downloaded from the github source 

I am not expecting a direct fix in any way since I know this is a very difficult project to get done. Most games run well on the emulator and the game I am trying to run actually runs better on this app than it did on nds4ios, I also know that many of the game issues will be improved once GNU Lightning JIT and  OpenGL ES rendering are implemented or optimized. I have been trying to run super mario 64 ds on the emulator and it crashes after a while , it is also a bit slow and is a bigger process for the app to handle. But I am mentioning this in order to let you know especially when it comes to debugging that this game seems to have trouble running on the emulator. This game could help you test out the performance of the emulator and also could be a goal to achieve. otherwise the emulator runs pretty well.

**Comment by WilliamLCobb** [comment]
You were right! Mario 64 was super buggy but just because of 1 small thing. I'm not really sure what was causing is but I put in a few checks that should increase stability a lot. I couldn't play all before but now I've managed to play an hour with no crashes.

**Comment by pmp174** [comment]
Omg that's awesome mate .
