### ISSUE TITLE
App Crashes when trying to open cheat menu during emulation.

### ISSUE THREAD

**Issue by MistieKitteh** [WilliamLCobb/iNDS#50]
iOS Devices: iPhone 6 and iPad Air 2
iOS Version: iOS 9.2
Jailbreak Status: No Jailbreak
Downloaded From: Github
Version:1.3.3

Hit gear icon, followed by cheats. App will immediately crash.

" libc++abi.dylib: terminating with uncaught exception of type NSException "

**Comment by WilliamLCobb** [comment]
All games or just a single game?
And has it ever opened?

**Comment by brujo5** [comment]
Same here, crashes when hit cheats

Iphone 6s jalibroken

**Comment by WilliamLCobb** [comment]
Fucking Xcode decided to stop copying the cheats database. Should be fixed now

**Comment by brujo5** [comment]
Thank you!!
