### ISSUE TITLE
iNDS Does Not Launch on an iPhone 5S running iOS 8.4

### ISSUE THREAD

**Issue by SE2Dev** [WilliamLCobb/iNDS#51]
iNDS (Installed via the Cydia Repository) does not launch successfully on a jailbroken iPhone 5S iOS 8.4, this has been the case since I first attempted to launch it (1.2.1 was the most recent version at the time); This issue is still present in versions as recent as 1.3.4. 

The following fixes have been tried and have failed:
* Restarting the device
* Respring the device
* Launching while in safe-mode
* Reinstalling / Updating iNDS

**Comment by WilliamLCobb** [comment]
Very weird. Do you have crash reporter? or any way you can get me your crash logs?

**Comment by WilliamLCobb** [comment]
It has never opened right?

**Comment by SE2Dev** [comment]
Correct, it never successfully opened.
I've forwarded the crash logs to willlcobb@gmail.com.

**Comment by SE2Dev** [comment]
As of version 1.3.5 iNDS now launches successfully (both the Cydia and iEmulators versions), however adding files via iTunes' file sharing only works with the iEmulators version, presumably because the Cydia version doesn't install in the same app directory as the iEmulators version. Manually placing files in /User/Documents/iNDS/ or /var/mobile/Documents/iNDS/ causes them to show up successfully.
