### ISSUE TITLE
Pokemon volt white crash

### ISSUE THREAD

**Issue by Xaehcaer13** [WilliamLCobb/iNDS#55]
After defeating the elite 4 iNDS crashes every time N's castle appears. Is there a solution to fix this? (Not jail broken, iPhone 6 9.2)

**Comment by MistieKitteh** [comment]
This appears to be the same issue as https://github.com/WilliamLCobb/iNDS/issues/54 and https://github.com/WilliamLCobb/iNDS/issues/53. 
Please follow the instructions for reporting issues and check for duplicates before posting. Thank you.

**Comment by pmp174** [comment]
Got to issue #56
