### ISSUE TITLE
Pause files

### ISSUE THREAD

**Issue by ericmarkmartin** [WilliamLCobb/iNDS#57]
iNDS keeps creating pause files.

**Comment by pmp174** [comment]
This is an automatic feature the app has so that when you leave the app your game state isn't erased. A good request would be the ability to turn this feature off but for the most part it shouldn't be an issue.

**Comment by ericmarkmartin** [comment]
But it keeps creating them. Even when I'm just in the app but not doing anything.

**Comment by pmp174** [comment]
thats weird it's only supposed to create a pause and overright everytime it creates them.

**Comment by WilliamLCobb** [comment]
Fixed in 1.5.0
