### ISSUE TITLE
Pokemon Heart Gold/Soul Silver [still having bugs]

### ISSUE THREAD

**Issue by hector0406** [WilliamLCobb/iNDS#58]
Pokemon Black/Black 2 run flawlessly. But I'm still having glitches with Pokemon Heart Gold (see attached images). In addition to the attached images, you can see some "black dots" while you are running or riding the bicycle.

Latest iNDS version (1.3.5) from iPwnStore
iPhone 6s Plus, iOS 9.2

![image](https://cloud.githubusercontent.com/assets/16678403/12285026/db791080-b983-11e5-807d-6e6e1865a7b0.png)
![image](https://cloud.githubusercontent.com/assets/16678403/12285027/db96037a-b983-11e5-9cf5-4ba8888395ff.png)
![image](https://cloud.githubusercontent.com/assets/16678403/12285028/db98d668-b983-11e5-855b-6648fd868482.png)
![image](https://cloud.githubusercontent.com/assets/16678403/12285029/dba04132-b983-11e5-8356-ec46643530e3.png)

**Comment by pmp174** [comment]
Please move any rom issues to #56 . Opening up individual issues for specific roms makes it difficult to keep track of rom issues.

**Comment by WilliamLCobb** [comment]
Yea this is a problem with DeSmuME and I think they still haven't figured it out even in their latest release (as far as I know). I follow their source forge updates though so when they do fix it I'll add the fix to iNDS

**Comment by ptzulu** [comment]
I think i just double posted something like this! Sorry! But then again, on desmume (mac at least) there is no problem, it works flawlessly, and so does OpenEmu (the only two i tested). But, to be fair, it was a patched rom. But on iNDS that same patched rom does not work, and has the same symptoms as described here.

**Comment by DarknesGaming** [comment]
There's a new version of iNDS @ptzulu, but you might have to build it with Xcode.
Also, DeSmuME 0.9.10 is kind of problematic, which might explain why I keep crashing in the dreamyard for Pokemon Black.

**Comment by WilliamLCobb** [comment]
Refer to Issue #78
