### ISSUE TITLE
How do I properly update using Xcode?

### ISSUE THREAD

**Issue by Zenivo** [WilliamLCobb/iNDS#6]
I just want to know for sure. Do I just rebuild the app and will it merge? Or will it create a second app? Because I don't want to redownload the rom, as it took me a few hours to find a working Pokemon White.

**Comment by WilliamLCobb** [comment]
I haven't tried this so hopefully someone else who is downloading the updates can help. If you've downloaded it through the command line with git, you should be able to close the project, pull the latest version, and reopen it with no problems. If you downloaded the zip, I think you can just download the newest zip version and open it in xcode and run and your games/saves will still be there. Hopefully I can get in contact with the buildstore or iEmulators soon so people won't need to do this for every update.

**Comment by pmp174** [comment]
Remember or copy the prefix that's somethings like com.example.inds then download the master and replace it with the newer version in the user folder. After that open xcode and change the prefix with the one you used originally. Then run it should update.

**Comment by Zenivo** [comment]
Thanks for the help! It worked perfectly.
