### ISSUE TITLE
INDS install problem

### ISSUE THREAD

**Issue by Lleonidas** [WilliamLCobb/iNDS#61]
iOS device: iPad Air 2
iOS version: iOS 9.2
Jailbreak status: no jailbreak
Download location: iEmulators - http://iemulators.com/inds
Current iNDS Version: 1.3.5
![image](https://cloud.githubusercontent.com/assets/16719667/12353987/fd7a1d08-bb92-11e5-9c6c-d12fa9d6c617.png)

**Comment by pmp174** [comment]
This is most likely being caused by an expired signature and is not an INDS issue. If you want look for someone who can build you a copy of INDS or get a buildstore account.

**Comment by deviorer** [comment]
Hi it is the same for me I have iOS 9.2.1 on iPhone 6 and it was working fine before and then it wouldn't open I tried to reinstall and it couldn't be downloaded at this time. Help?

**Comment by Pepperoony** [comment]
Now I can't install from the Buildstore, getting the same error as everybody above

**Comment by WilliamLCobb** [comment]
Definitely a signature problem or something similar. I would ask the build store. They said today on Twitter they were having problems

**Comment by deviorer** [comment]
Yea I was trying the buildstore and it didn't work... Anyone out there can send a build?
