### ISSUE TITLE
@william cobb is this video real?

### ISSUE THREAD

**Issue by brujo5** [WilliamLCobb/iNDS#65]
https://www.youtube.com/watch?v=Zomi4XzHGdE&index=1&list=LL4iB0-Qu8X7APAzBNshYasA

dolphin emulator on iOS

**Comment by pmp174** [comment]
Yes he posted it on Twitter😊

**Comment by brujo5** [comment]
these people do not believe?

https://forums.dolphin-emu.org/Thread-dolphin-run-full-speed-on-ios-how-is-that?pid=397393#pid397393

**Comment by WilliamLCobb** [comment]
Yep. It's not running like past emulators have. I don't wan to give too much away yet but I'm making an app that will let you run any emulator on your phone (including 3DS) and will be available in the app store

**Comment by brujo5** [comment]
that great

but It will not be available for long on iOS, because Apple's policies says Emulators = piracy

**Comment by WilliamLCobb** [comment]
I'm going to try to get around that but if I can't I'll still release it on iEmulators and build store

**Comment by brujo5** [comment]
that great
I would be willing to pay for a dolphin port, just like zottd emulators on cydia

**Comment by pmp174** [comment]
Will you make a github source?

**Comment by WilliamLCobb** [comment]
3DS is also working (As well as it does on pc and mac) So that will be included as well

**Comment by WilliamLCobb** [comment]
I think so once I finish just to show other developers how I did it. I plan on selling it in the app store though and would like to get it there before I open it up

**Comment by pmp174** [comment]
Which emulator core do you use for 3DS and be careful apple can ban and revoke accounts if they get bitchy.

**Comment by pmp174** [comment]
If you post it on the app store I need to get the notification right away so I could buy it before apple tries to take it down.

**Comment by Pepperoony** [comment]
What kind of fps are we talking on the latest hardware? Something near 30? How big are file sizes for the average game? For example, Wind Waker after being compressed onto iOS


--


Luke Rooney/ Manager of Marketing
luke.rooney@servitehs.org(mailto:luke_rooney@icloud.com)/(562)-360-4258(tel:(562)-360-4258)


Trinity Corporation
ServiteHS.org
1952 W La Palma Ave, Anaheim(x-apple-data-detectors://5/2)

**Comment by WilliamLCobb** [comment]
It uses your computer to help emulate the game so it should be 60 fps for most newer computers. It will also feature a bunch of cool features like co-op across devices and built in multiplayer

**Comment by Pepperoony** [comment]
How does it use a computer? Not sure I follow sorry

**Comment by pmp174** [comment]
I think its a streaming app instead of an actual emulator unless it is more complex.

**Comment by WilliamLCobb** [comment]
It's a little bit more complex than that but basically. I figured instead of running the emulation on the phone, it would be much easier to offload it to the computer and send back the results

**Comment by pmp174** [comment]
Its a good idea and could also benefit if it were like an on live service where it would run off a server (even though that was a commercial failure).  The only issue would be not everyone has a donor device (computer) and playing on the go would be hindered

**Comment by WilliamLCobb** [comment]
I agree, there are a lot of draw backs. But I've successfully played over a LTE connection from a computer in a different city. I tried to find a way to put Dolphin on iOS but I think it's going to be awhile before the technology is there or a dedicated team comes in to rewrite it for iOS. 

Plus it can adapt to any game or emulator. SO anything from 3DS to Skyrim or Civilization could theoretically be played on it. I've just been optimizing it for Dolphin for testing (And I want to play Mario Sunshine).

Here's another video of it that looks a lot less fake: https://www.youtube.com/watch?v=1IwfFLZY6KQ

**Comment by pmp174** [comment]
The video is private but I trust you are making something great

**Comment by WilliamLCobb** [comment]
Oops, changed it

**Comment by mk8itra1n** [comment]
@WilliamLCobb this app that lets you run any emulator sounds amazing and the fact you got 3DS emulation is badass👍👌 Will there be Sega Dreamcast support as support for the reicast emulator for iOS came to a halt?

**Comment by WilliamLCobb** [comment]
Yea I'll work to support every emulator and then Mac and PC games. I'm going to make it extensible so I and other developers can write plugins to assist streaming any game. Right now I've only written the Dolphin and Citra plugins but theoretically any desktop game will be compatible.

**Comment by pmp174** [comment]
it would be cool to install this on home server or even a mac mini and use it anywhere.

**Comment by WilliamLCobb** [comment]
Yea that's the plan.

**Comment by mk8itra1n** [comment]
@WilliamLCobb Any ETA on when this emulator will be released and where it's being released too?(Cydia, AppStore, build store, etc.)

**Comment by WilliamLCobb** [comment]
I'll start beta testing this week or next week and could see it on the App Store a few weeks from now
