### ISSUE TITLE
iNDS emulator not opening

### ISSUE THREAD

**Issue by Jayk723** [WilliamLCobb/iNDS#68]
Hi, I recently tried opening my iNDS, but it doesn't work. It keeps on going back to my home screen. What should I do to fix this?

**Comment by pmp174** [comment]
Where did you download it?

**Comment by Jayk723** [comment]
i downloaded it from http://iemulators.com/

**Comment by pmp174** [comment]
@Jayk723 the developer of this app does not post on iemulators. The issue is based on an expired certificate. You may be able to find resources here. https://github.com/WilliamLCobb/iNDS/wiki/Building-INDS-for-Jailed-iDevices  this issue should be closed.

**Comment by um10** [comment]
I don't know why but mine not working

**Comment by pmp174** [comment]
@um10 if you download from iemulators the certificate is revoked.

**Comment by um10** [comment]
😢 I know!  U know if is going to be an update or other places where I can download?

**Comment by um10** [comment]
Pmp174?

**Comment by WilliamLCobb** [comment]
You can install it from the source if you have a Mac computer. Refer to the wiki for directions
