### ISSUE TITLE
Side-By-Side Screens in Landscape mode

### ISSUE THREAD

**Issue by OkazakiTheOtaku** [WilliamLCobb/iNDS#7]
Would it be possible, in a future version, to have an option for this? As in, when you put your iPhone/iPad into landscape, the two screens go side-by-side instead of stacking and shrinking?

MFi support is already built into the app, but a tad cumbersome because when using a MFi mount, it shrinks the entire screen. If this is added/improved it would make the entire experience A+

**Comment by WilliamLCobb** [comment]
Yea soon you'll be able to move both screens around and resize too.

Also I plan on working on MFi but I need to find an MFi device to test with first

**Comment by OkazakiTheOtaku** [comment]
The MFi support is perfect, I have a CTRLi and it's flawless. Just the screen shrinking is the issue.

But it sounds like you're working on it, which is great! Thanks!

**Comment by WilliamLCobb** [comment]
Would you mind sending me a picture?

Sent from Outlook




On Wed, Dec 2, 2015 at 3:36 PM -0800, "OkazakiTheOtaku" <notifications@github.com> wrote:












The MFi support is perfect, I have a CTRLi and it's flawless. Just the screen shrinking is the issue.



But it sounds like you're working on it, which is great! Thanks!

**Comment by OkazakiTheOtaku** [comment]
Of what? The controller?

**Comment by WilliamLCobb** [comment]
Yea the screen or whatever is shrinking. I don't have a controller yet but maybe I can still fix it if I can see what it's doing
Sent from Outlook




On Wed, Dec 2, 2015 at 3:44 PM -0800, "OkazakiTheOtaku" <notifications@github.com> wrote:












Of what? The controller?

**Comment by OkazakiTheOtaku** [comment]
Oh, it does the same thing as when a controller isn't connected. http://imgur.com/fFwILfg

**Comment by WilliamLCobb** [comment]
Oh okay that makes sense. Yea in a version coming out soon you'll be able to re arrange those to be full screen.

**Comment by OkazakiTheOtaku** [comment]
Sweet! Looking forward to that! 

It will, in my book, be a pretty much perfect emulator then.

**Comment by OkazakiTheOtaku** [comment]
I hate to reopen a closed issue, but was it closed because it was implemented? Or just because I never closed it?

**Comment by WilliamLCobb** [comment]
Implemented in version 1.2.0. You can move almost everything now

**Comment by OkazakiTheOtaku** [comment]
Oh sweet! Thank you so much for all the work you've done!

**Comment by pmp174** [comment]
This is awesome!!!! Best update ever!!

**Comment by WilliamLCobb** [comment]
No problem! It's starting to actually be playable for most games.

**Comment by pmp174** [comment]
I recommend you make the default layout different on the ipad some new users might be confused. I was confused until I realized it was changible .

**Comment by WilliamLCobb** [comment]
Definitely. I'll probably add a tutorial soon too. There are still a few bugs in this version though so make sure to re download the new source tomorrow.

**Comment by mkemntz** [comment]
How do i get the top screen of the iNDS Pokemon game to screen mirror onto my tv?
It only shows the menu screen; defeating the purpose of screen mirroring the game.
