### ISSUE TITLE
Cheat Codes

### ISSUE THREAD

**Issue by kingriddle123** [WilliamLCobb/iNDS#71]
Hey I love the new emulator. It works great. I was just wondering the ETA for cheat codes for games? Could you implement the cheat code system already in desmume into iNDS? thanks

**Comment by DarknesGaming** [comment]
The cheat code system was already implemented into iNDS. There was just no way to actually turn the cheats on @kingriddle123.
@WilliamLCobb just updated iNDS though and now you can use cheats. Have fun!
