### ISSUE TITLE
Crash after launch

### ISSUE THREAD

**Issue by Alphablaze98** [WilliamLCobb/iNDS#73]
After opening the app and downloading 3 different roms I attempted to launch the games. After selecting launch normally the game goes from 60 fps down to 0 and instantly crashes.

iPhone 6s
iOS 9.2.1
Non-jailbroken
Downloaded to the home screen (side loaded from Xcode)
Running iNDS 1.3.1

**Comment by pmp174** [comment]
What rom is giving you these issues.

**Comment by WilliamLCobb** [comment]
This was due to an optimization flag present in 1.3.1. Should be fixed in newer versions
