### ISSUE TITLE
Downloads location

### ISSUE THREAD

**Issue by kingriddle123** [WilliamLCobb/iNDS#74]
Hey guys i found the location of where the roms are kept in ifile. Just go into ifile, click the home button at the bottom, then go to containers-> data-> and look in the folders for inds. If you bought ifile, then jsut search in the hierarchy for inds. Once you find the folder, navigate to the folder inside called iNDS. Inside that folder you will find the roms in their .nds form. You can import roms there by copying and pasting into that folder as .nds or from safari as a zip file containing the rom, click open in and choose inds. It will unzip the rom into the iNDS folder mentioned above. Inside the iNDS folder you will also find a folder named battery. This is where saves are kept as .dsv files. Don't try to import files of the same type as they wont link and in the end they will fail. Inside the apps folder there is also a folder labeled Inbox. That folder will contain all the failed attempts to import roms. Weather they were an unusable file type ( only working are zip and inds as said above), or if the file size exceeded your remaining memory, whatever the reason, any failed attempts will be there and will clog your memory. I recommend that in the future, Cobb should add a smash cache button to empty this folder. Cleaning apps and tweaks wont delete from this folder as it is classified as part of the apps infrastructure. To empty the folder, simply manually delete the files and empty the trash and you'll be good to go.  Thats all the info i have for now. I'll update once i learn more.

**Comment by pmp174** [comment]
Or you can just add them using the itunes document sheet

**Comment by WilliamLCobb** [comment]
Ahh they should be automatically deleted now. Thanks
