### ISSUE TITLE
Adding cheat codes ?

### ISSUE THREAD

**Issue by Wil9620** [WilliamLCobb/iNDS#76]
Hello,

I'd like to know what type of codes we can add to games, because all included cheats are working, but I tried many action replay codes but none of them work...

Thanks !

**Comment by Cooliodex** [comment]
I'm not sure if they're working now, but Action Replay codes have certainly worked in the past. Maybe its on your end or the current version is broken in some way.

**Comment by Wil9620** [comment]
Ok thanks, don't know why they don't work...

I'm using codes that work with my DS Action Replay, so I know the issue can't be the codee itself...

Another strange thing is that cheat codes already included in iNDS list are all working for me.

**Comment by WilliamLCobb** [comment]
Different versions of roms require different cheat codes. So cheats for the US Mario version are slightly different than a universal version, even though they seem identical. When you go to enter a cheat, the game code is displayed next to Game Id: 

You can usually google the game code and the word cheats and a ton of lists with cheats for tat game will come up. 

Let me know if that doesn't work and I'll test out the cheats you're using

**Comment by Wil9620** [comment]
Thank you for your answer.

I'm trying to use cheat codes for the game Pokemon Diamond version (FR) that I got here : http://www.emuparadise.mobi/Nintendo_DS_ROMs/Pokemon_Version_Diamant_(v05)_(F)(FireX)/47322-download

One of the cheat codes I'vre tried to use is the one that lets you walk through walls. I found it here : http://www.pokemontrash.com/codes-pokemon/codes-diamant-perle-mouvement.php#aller-partout

The name of the code is "Traverser les murs v2". Normally, when using the code, you must press R+B to activate it and L+B to disable it, but it didn't work for me.

I used the same code on my NDS with an Action Replay, and it worked, so the code seems correct.

**Comment by Wil9620** [comment]
Sorry but I forgot something else,
for all my games there is a strange thing about the game id : it's always showing the same one (ADAF), like you can see here : http://prnt.sc/a97gmx
Don't know if it could be an issue too.

**Comment by DarknesGaming** [comment]
Seems like a problem. Maybe someone will get to you as soon as possible.

**Comment by Wil9620** [comment]
I hope so, seems like I'm the only one to have that issue :/

**Comment by WilliamLCobb** [comment]
Very weird. So every single game you enter cheat codes for shows the same id?

**Comment by Wil9620** [comment]
That's it, for every single game I get the same game id (ADAF)... don't know what I'm doing wrong :/

**Comment by WilliamLCobb** [comment]
It's not you I must have messed something up. I'm taking a look at it

**Comment by Wil9620** [comment]
Ok, thanks !

**Comment by DarknesGaming** [comment]
That was (kind of) quick.

**Comment by WilliamLCobb** [comment]
Should be fixed in 1.5.1

**Comment by TheShiningRose** [comment]
Can you enter action replay codes now?
