### ISSUE TITLE
Ethical recommendation & ui issue

### ISSUE THREAD

**Issue by pmp174** [WilliamLCobb/iNDS#8]
The previous developers who made nds4ios and Nitrogen were forced to remove the search features because of legal issues with nintendo. I am not completely certain but I recommend you encourage people to use the open in from safari when downloading a rom or use a web server like provenance uses to import roms ( https://github.com/jasarien/Provenance ) instead of the search/browser feature. This addition would help you so that you don't get into legal problems with nintendo who hates developers. You could also remove the feature and show people  how to re-add it to the app in the wiki so that you don't get into legal issues. Just looking out because nintendo is full of d-heads if you know what i'm saying .

**Comment by WilliamLCobb** [comment]
Good idea, might move it to google like GBA4iOS

**Comment by pmp174** [comment]
Move what to google? The project ? Google code is being shut down soon.

**Comment by pmp174** [comment]
Yes that would be better

**Comment by pmp174** [comment]
![image](https://cloud.githubusercontent.com/assets/15956420/12024730/43e7b39e-ad75-11e5-996b-41edb40d73c9.png)

I still recommend you change the site to google to stay away from nintend*** heads and the done button looks funny

**Comment by WilliamLCobb** [comment]
Yea I'll probably copy what GBA4iOS did and allow you to set your home page

**Comment by WilliamLCobb** [comment]
Fixed in latest commit

**Comment by pmp174** [comment]
perfect now does nintendogs cant say one thing.
