### ISSUE TITLE
iNDS crashes as soon as I tap it

### ISSUE THREAD

**Issue by throwaway8471** [WilliamLCobb/iNDS#80]
On an iPhone 5
Downloaded from build store

**Comment by pmp174** [comment]
Like said in many issues before this has to do with a bad certificate. Try redownloading the app from the build store. The developer of this app doesn't supervise build store certificates.

**Comment by throwaway8471** [comment]
Didn't work

**Comment by pmp174** [comment]
You have to contact build store support

**Comment by nickdoggy** [comment]
i download this app in buildstore.and  i have the buildstore account and paid it.the app worked well before.but i downloaded it2 days ago  inbuildstore 2 days ago it crashed...so sad.could you give me any help.thank you

**Comment by cmmc38** [comment]
Same issue here. I contacted Build Store support and they said:

Hi there, sorry for the delay
If your @iNDSapp crashes at launch – don’t panic! We’d contacted the developers and fix is coming. Stay tuned and be patient, please.

Out of curiosity, what was the issue that popped up?

**Comment by nickdoggy** [comment]
still crashed，，sad

发自我的 iPhone

**Comment by WilliamLCobb** [comment]
Should be fixed in 1.4.0. Please re open if iNDS still crashes on launch after updating.

**Comment by nickdoggy** [comment]
thank you.

发自我的 iPhone
