### ISSUE TITLE
Download not working

### ISSUE THREAD

**Issue by DarknesGaming** [WilliamLCobb/iNDS#81]
iOS Device: iPhone 6
iOS Version: 9.2.1
Jailbroken status: NO
Download location: From iEmulators
Current iNDS Version: 1.3.5
Side Note: Since your emulator uses the DeSmuMe arm interpreter, you should update it to the latest version (0.9.11). For some reason, people keep saying NOT to use 0.9.10 due to some issues.

**Comment by DarknesGaming** [comment]
I almost forgot: Download DeSmuMe 0.9.11 at the following link:
http://www.desmume.org

**Comment by WilliamLCobb** [comment]
Downloads should be fixed now

Upgrading to DeSmuMe 0.9.11 is going to be hard since a ton of modifications have been made for the current version to run on iOS but I'm working on it
