### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by marcojose18** [WilliamLCobb/iNDS#82]
I cant open the app sir. I cant open it. It crashes everytime i open it. I havent seen the inside of the app ever since. Im at ios 9.2.1

**Comment by pmp174** [comment]
Where did you download it?

**Comment by DarknesGaming** [comment]
That's a good question: Where did you download it marco?
You can try re-installing the app. Since you said it keeps crashing, you most likely don't have a Jailbroken device.

**Comment by WilliamLCobb** [comment]
Still hitting my head against the wall trying to figure this out. I'm going to try to hold off loading things like dropbox until the app successfully opens and hopefully it will fix the problem.

**Comment by pmp174** [comment]
dont hurt yourself @WilliamLCobb XD

**Comment by WilliamLCobb** [comment]
Haha I think it's fixed. Turns out the Build Store has trouble signing embedded frameworks. The solution was to remove UnrarKit.framework from the app when I send them a version
