### ISSUE TITLE
iNDS Beta Branch?

### ISSUE THREAD

**Issue by DarknesGaming** [WilliamLCobb/iNDS#87]
A new branch for iNDS might be good for the project, considering it's a beta version. People can test drive new features, and report bugs they find so they can be fixed. Speaking of which, TinyXML2 is made to be lighter than TinyXML, AsmJit is updated, and DeSmuME 0.9.11 source code is out, and I have not tested any of them on iOS yet. That's also a reason why I think we should build a beta branch for iOS lol.
WARNING: Not for everyday use.

**Comment by DarknesGaming** [comment]
Don't give me a tl;dr summary. It's just sad, and suggests that people are lazy to read.

**Comment by DarknesGaming** [comment]
Did you upload iNDS 1.4.0 to iEmulators yet? I depend on that website to get a DS emulator.

**Comment by WilliamLCobb** [comment]
I made a beta branch that tests out new features and other developers can help me with.

Unfortunately I don't control when apps are released on iEmulators. They have to buy an enterprise certificate to sign the app and those aren't easy to come by and are probably pretty expensive. Once I get the microphone working I'll let the owner know and hopefully he can get a new version out.

**Comment by DarknesGaming** [comment]
This will be awesome! I just need to start learning code for development, because all I know is HTML and CSS.

**Comment by DarknesGaming** [comment]
I just need to learn Cocoa, Swift, C++, and maybe tons of other codes. That way, I can modify the DeSmuME 0.9.11 code more easily so it can work with iOS without being incredibly slow.
