### ISSUE TITLE
8 FPS on iPad 4

### ISSUE THREAD

**Issue by Jarmfam** [WilliamLCobb/iNDS#89]
Everything was working perfectly, when yesterday everything slowed down to 8 FPS. Before, it was running at 55 FPS. I don't know what happened. Did I do something, or is it a glitch?

**Comment by DarknesGaming** [comment]
It's probably a glitch. @WilliamLCobb will probably fix it, but for now, try to reload the ROM when it slows down to a snail's pace.

**Comment by WilliamLCobb** [comment]
Did the fps randomly drop or did it drop after you opened the menu?

**Comment by Jarmfam** [comment]
I just opened the app one day, and it started running at 8 FPS. It never went back up. I loaded another ROM, closed the app, restarted my iPad and it still runs at 8 FPS. Before it was running at 60 FPS. And I've tried almost 10 different games. Should I uninstall it and install it again?

**Comment by essiw** [comment]
This might be caused by continuously synching (due to an other bug)? Can you start up if and "synching starts" appears wait until "synching complete" appears and then start the game? Synching decreases the FPS of the game, that is why I think that might be the problem.

**Comment by Jarmfam** [comment]
I just tried that and it's still at 8 FPS.

**Comment by DarknesGaming** [comment]
You can try turning Dropbox Sync off and see if that works. You can also try turning off all the features except show FPS. If that doesn't work, we have a problem.
I almost forgot: You never told us your iNDS version (bottom of the settings screen), if you're Jailbroken (it is if you have Cydia), and where you downloaded iNDS from.

**Comment by DarknesGaming** [comment]
@Jarmfam Can you tell us what iOS you're on, followed by your iNDS version, if you're Jailbroken (Cydia is installed), and where you downloaded iNDS from? That might help us.

**Comment by Jarmfam** [comment]
Sorry for taking so long to respond, but I'm on 1.40, and I got it here, on GitHub. Also, it isn't Jailbroken.

**Comment by WilliamLCobb** [comment]
I just rewrote the throttle system so hopefully that will fix it in the next update

**Comment by Jarmfam** [comment]
In case you need it, here's a video going into more detail on the problem.
https://drive.google.com/open?id=0B8BiinUaN3oMT1prT3pYOUdGQ2s

**Comment by WilliamLCobb** [comment]
Wow that's really weird. Try turning off bicubic interpolation in the the emulator settings and restarting the app.

**Comment by Jarmfam** [comment]
That worked perfectly! Thank you so much!
