### ISSUE TITLE
Dutch localisation

### ISSUE THREAD

**Issue by essiw** [WilliamLCobb/iNDS#94]
@WilliamLCobb I have made a Dutch localisation for you. The abbreviation for the Netherlands is NL. I tried to figure out how to add this the normal way but I have never used github so I guessed it would be easier to do it this way. I am not sure if a Dutch localisation is wanted (most dutch speak english, so it probably only is necessary for a small amount of people) but here you go anyway :) I put it in a normal text document named it after how other localisations where named (not sure if that is the correct way to make such file). I can provide updates when necessary.

[Localizable.strings.txt](https://github.com/WilliamLCobb/iNDS/files/220723/Localizable.strings.txt)

**Comment by pmp174** [comment]
Shouldn't you make this into a pull request?

**Comment by essiw** [comment]
I tried to say in my post that I have no clue how to actually make a good pull request and it seems like my file is not correctly formatted either. That is why I did like this.

**Comment by pmp174** [comment]
https://help.github.com/articles/creating-a-pull-request/

**Comment by WilliamLCobb** [comment]
Thank you! I added it
