### ISSUE TITLE
[Question] Restoring Saves

### ISSUE THREAD

**Issue by kalkr** [WilliamLCobb/iNDS#97]
Hey.

I have a question about restoring saves from my Mac. I have a few backups on my Mac, and I ended up having to delete iNDS because of a bug, and am now wondering how I can restore theses saves. Anything helps. :)

Thanks,
-me

**Comment by essiw** [comment]
There are two ways, the first is via iTunes. Open iTunes, go to your device and select apps. Then scroll all the way down to select iNDS. Take the battery folder and copy (by moving) it to your computer. Open that folder and put your save files in there. Then move the battery folder back into iTunes and select replace.

The other way involves dropbox synch. Synch with dropbox from within iNDS and put your backup files in the dropbox folder created by iNDS. Force quit iNDS and open it again, be sure to wait until it says "synching complete" and start your game.

**Comment by kalkr** [comment]
Thank you. :)

I'll try that later to see how it goes when I'm not busy.

**Comment by WilliamLCobb** [comment]
The fixes @essiw should work

You can also save them on another app on your phone and use the ios "Open In" and open them in iNDS.
